# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfibonacci',
            name='time_elapsed',
            field=models.CharField(max_length=255),
        ),
    ]
